### ISSUE TITLE
How to compile and run this on a device?

### ISSUE THREAD

**Issue by alexshk** [b3ll/Ignition#41]
Is there any howto? Do I need jailbreak for this?

Thanks

**Comment by hongliang-goudou** [comment]
Hi @alexshk , yes, you need to jailbreak your iPad. Currently Ignition only supports iOS 8.1.x.

The easiest way of run Ignition on your iPad is through Cydia. Just open Cydia and search Ignition and there you go.

**Comment by alexshk** [comment]
Thanks @hongliang-goudou
